version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data          # Volumen para persistir los datos
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Monta el script de inicialización
    networks:
      - app-network

  app:
    build:
      context: .                                          # Carpeta donde está tu Dockerfile
      dockerfile: Dockerfile                              # Nombre del Dockerfile (opcional si es "Dockerfile")
    container_name: springboot-app
    ports:
      - "8080:8080"                                       # Expone el puerto 8080 para la app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/product_catalog
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres                                          # Asegura que PostgreSQL se inicie antes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
