version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data          # Volumen para persistir los datos
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Monta el script de inicialización
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
