name: CI - Java Spring Boot with Docker

on:
  push:
    branches:
      - master  # Se ejecutará en cada push a la rama master
  pull_request:
    branches:
      - master  # Se ejecutará en cada pull request hacia la rama master

jobs:
  build:
    runs-on: ubuntu-latest  # Utilizamos un runner de Ubuntu

    steps:
      # 1. Hacemos el checkout del código
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Configuramos Java 
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  

      # 3. Instalamos las dependencias y compilamos el proyecto usando Maven 
        run: mvn clean install -DskipTests=true  

      # 4. Ejecutamos las pruebas unitarias 
      - name: Run tests
        run: mvn test  
      # 5. Construcción de la imagen Docker utilizando el Dockerfile de múltiples etapas
      - name: Build Docker image
        run: |
          docker build -t my-spring-boot-app .  # Construye la imagen Docker con el Dockerfile (multi-stage)

      
      
