name: CI - Java Spring Boot with Docker

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-22.04 

    steps:
      # 1. Hacer checkout del código del repositorio
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Configuración de Java 
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  
          distribution: 'temurin'  

      # 3. Instalamos las dependencias y compilamos el proyecto con Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests  

      # 4. Ejecutar las pruebas unitarias 
      - name: Run tests
        run: mvn test 

      # 6. Construcción de la imagen Docker utilizando el Dockerfile de múltiples etapas
      - name: Build Docker image
        run: |
          docker build -t my-dockerhub-username/my-spring-boot-app:${{ github.sha }} .
        

        
     
